<a href="https://colab.research.google.com/github/Thorbole666/AuthproRepo/blob/main/Penguindataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
df=pd.read_csv("/content/penguins.csv")

In [2]:
print(df)

    species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen            39.1           18.7              181.0
1    Adelie  Torgersen            39.5           17.4              186.0
2    Adelie  Torgersen            40.3           18.0              195.0
3    Adelie  Torgersen             NaN            NaN                NaN
4    Adelie  Torgersen            36.7           19.3              193.0
..      ...        ...             ...            ...                ...
339  Gentoo     Biscoe             NaN            NaN                NaN
340  Gentoo     Biscoe            46.8           14.3              215.0
341  Gentoo     Biscoe            50.4           15.7              222.0
342  Gentoo     Biscoe            45.2           14.8              212.0
343  Gentoo     Biscoe            49.9           16.1              213.0

     body_mass_g     sex
0         3750.0    MALE
1         3800.0  FEMALE
2         3250.0  FEMALE
3            NaN     NaN
4         3450.0  FEMALE
..           ...     ...
339          NaN     NaN
340       4850.0  FEMALE
341       5750.0    MALE
342       5200.0  FEMALE
343       5400.0    MALE

[344 rows x 7 columns]

In [3]:
df.head(5)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE

In [4]:
df.tail(5)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [5]:
df.values #display only values

array([['Adelie', 'Torgersen', 39.1, ..., 181.0, 3750.0, 'MALE'],
       ['Adelie', 'Torgersen', 39.5, ..., 186.0, 3800.0, 'FEMALE'],
       ['Adelie', 'Torgersen', 40.3, ..., 195.0, 3250.0, 'FEMALE'],
       ...,
       ['Gentoo', 'Biscoe', 50.4, ..., 222.0, 5750.0, 'MALE'],
       ['Gentoo', 'Biscoe', 45.2, ..., 212.0, 5200.0, 'FEMALE'],
       ['Gentoo', 'Biscoe', 49.9, ..., 213.0, 5400.0, 'MALE']],
      dtype=object)

In [6]:
df.shape #display rows and cols

(344, 7)

In [7]:
df.size #get number of element present

2408

In [8]:
df.ndim #get dimention of dataset

2

In [9]:
df.count() #It count  no of each element present in each column

species              344
island               344
bill_length_mm       342
bill_depth_mm        342
flipper_length_mm    342
body_mass_g          342
sex                  333
dtype: int64

In [10]:
df.dtypes #get data type of each col.

species               object
island                object
bill_length_mm       float64
bill_depth_mm        float64
flipper_length_mm    float64
body_mass_g          float64
sex                   object
dtype: object

In [11]:
df.empty#check whether empty elements present or not

False

In [12]:
df.head(2)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE

In [13]:
df['island'].is_unique #varname['column_name'].is_unique

False

In [ ]:
df.nunique()#get no of unique values in  each column

species                3
island                 3
bill_length_mm       164
bill_depth_mm         80
flipper_length_mm     55
body_mass_g           94
sex                    2
dtype: int64

In [ ]:
df.info()#gives col info,memory usage etc.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    object
 1   island             344 non-null    object
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object
dtypes: float64(4), object(3)
memory usage: 18.9+ KB

In [ ]:
df.describe()#it gives statistical information about dataset

       bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
count      342.000000     342.000000         342.000000   342.000000
mean        43.921930      17.151170         200.915205  4201.754386
std          5.459584       1.974793          14.061714   801.954536
min         32.100000      13.100000         172.000000  2700.000000
25%         39.225000      15.600000         190.000000  3550.000000
50%         44.450000      17.300000         197.000000  4050.000000
75%         48.500000      18.700000         213.000000  4750.000000
max         59.600000      21.500000         231.000000  6300.000000

In [ ]:
df.describe(include="object") #number object all

       species  island   sex
count      344     344   333
unique       3       3     2
top     Adelie  Biscoe  MALE
freq       152     168   168

In [ ]:
df.describe(include='all')

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
count,344,344,342.000000,342.000000,342.000000,342.000000,333
unique,3,3,NaN,NaN,NaN,NaN,2
top,Adelie,Biscoe,NaN,NaN,NaN,NaN,MALE
freq,152,168,NaN,NaN,NaN,NaN,168
mean,NaN,NaN,43.921930,17.151170,200.915205,4201.754386,NaN
std,NaN,NaN,5.459584,1.974793,14.061714,801.954536,NaN
min,NaN,NaN,32.100000,13.100000,172.000000,2700.000000,NaN
25%,NaN,NaN,39.225000,15.600000,190.000000,3550.000000,NaN
50%,NaN,NaN,44.450000,17.300000,197.000000,4050.000000,NaN
75%,NaN,NaN,48.500000,18.700000,213.000000,4750.000000,NaN
max,NaN,NaN,59.600000,21.500000,231.000000,6300.000000,NaN

In [ ]:
df.columns

Index(['species', 'island', 'bill_length_mm', 'bill_depth_mm',
       'flipper_length_mm', 'body_mass_g', 'sex'],
      dtype='object')

In [ ]:
df['species'] #varname['Column] -->Select particular column

0      Adelie
1      Adelie
2      Adelie
3      Adelie
4      Adelie
        ...
339    Gentoo
340    Gentoo
341    Gentoo
342    Gentoo
343    Gentoo
Name: species, Length: 344, dtype: object

In [ ]:
df[['species','island']] #varname[['col1','col2'..]]  --->select multiple columns

    species     island
0    Adelie  Torgersen
1    Adelie  Torgersen
2    Adelie  Torgersen
3    Adelie  Torgersen
4    Adelie  Torgersen
..      ...        ...
339  Gentoo     Biscoe
340  Gentoo     Biscoe
341  Gentoo     Biscoe
342  Gentoo     Biscoe
343  Gentoo     Biscoe

[344 rows x 2 columns]

In [ ]:
df.columns

Index(['species', 'island', 'bill_length_mm', 'bill_depth_mm',
       'flipper_length_mm', 'body_mass_g', 'sex'],
      dtype='object')

In [ ]:
df.nlargest(2,'body_mass_g')#display elements in desc to asc order
#varname()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
237,Gentoo,Biscoe,49.2,15.2,221.0,6300.0,MALE
253,Gentoo,Biscoe,59.6,17.0,230.0,6050.0,MALE

In [ ]:
df.nsmallest(5,'body_mass_g') #display elements in asc to desc order

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
190,Chinstrap,Dream,46.9,16.6,192.0,2700.0,FEMALE
58,Adelie,Biscoe,36.5,16.6,181.0,2850.0,FEMALE
64,Adelie,Biscoe,36.4,17.1,184.0,2850.0,FEMALE
54,Adelie,Biscoe,34.5,18.1,187.0,2900.0,FEMALE
98,Adelie,Dream,33.1,16.1,178.0,2900.0,FEMALE

In [ ]:
df.sample()#display random records

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
187,Chinstrap,Dream,47.5,16.8,199.0,3900.0,FEMALE

In [ ]:
df.axes

[RangeIndex(start=0, stop=344, step=1),
 Index(['species', 'island', 'bill_length_mm', 'bill_depth_mm',
        'flipper_length_mm', 'body_mass_g', 'sex'],
       dtype='object')]

In [ ]:
df.isna()#checks for null data. isna is primary function

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False
3,False,False,True,True,True,True,True
4,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...
339,False,False,True,True,True,True,True
340,False,False,False,False,False,False,False
341,False,False,False,False,False,False,False
342,False,False,False,False,False,False,False
343,False,False,False,False,False,False,False

In [ ]:
df.isnull()#checks for null data and isnull is alias

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False
3,False,False,True,True,True,True,True
4,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...
339,False,False,True,True,True,True,True
340,False,False,False,False,False,False,False
341,False,False,False,False,False,False,False
342,False,False,False,False,False,False,False
343,False,False,False,False,False,False,False

In [ ]:
df.index #get information such as its range like  start,end and sv

RangeIndex(start=0, stop=344, step=1)

In [ ]:
df.empty#check whether dataset is empty or not

False

In [ ]:
df.T#T is transpose which converts rows to cols and cols to rows.

,0,1,2,3,4,5,6,7,8,9,...,334,335,336,337,338,339,340,341,342,343
species,Adelie,Adelie,Adelie,Adelie,Adelie,Adelie,Adelie,Adelie,Adelie,Adelie,...,Gentoo,Gentoo,Gentoo,Gentoo,Gentoo,Gentoo,Gentoo,Gentoo,Gentoo,Gentoo
island,Torgersen,Torgersen,Torgersen,Torgersen,Torgersen,Torgersen,Torgersen,Torgersen,Torgersen,Torgersen,...,Biscoe,Biscoe,Biscoe,Biscoe,Biscoe,Biscoe,Biscoe,Biscoe,Biscoe,Biscoe
bill_length_mm,39.1,39.5,40.3,NaN,36.7,39.3,38.9,39.2,34.1,42.0,...,46.2,55.1,44.5,48.8,47.2,NaN,46.8,50.4,45.2,49.9
bill_depth_mm,18.7,17.4,18.0,NaN,19.3,20.6,17.8,19.6,18.1,20.2,...,14.1,16.0,15.7,16.2,13.7,NaN,14.3,15.7,14.8,16.1
flipper_length_mm,181.0,186.0,195.0,NaN,193.0,190.0,181.0,195.0,193.0,190.0,...,217.0,230.0,217.0,222.0,214.0,NaN,215.0,222.0,212.0,213.0
body_mass_g,3750.0,3800.0,3250.0,NaN,3450.0,3650.0,3625.0,4675.0,3475.0,4250.0,...,4375.0,5850.0,4875.0,6000.0,4925.0,NaN,4850.0,5750.0,5200.0,5400.0
sex,MALE,FEMALE,FEMALE,NaN,FEMALE,MALE,FEMALE,MALE,NaN,NaN,...,FEMALE,MALE,NaN,MALE,FEMALE,NaN,FEMALE,MALE,FEMALE,MALE

In [ ]:
df.memory_usage()#indicate memeory used by each column

Index                 132
species              2752
island               2752
bill_length_mm       2752
bill_depth_mm        2752
flipper_length_mm    2752
body_mass_g          2752
sex                  2752
dtype: int64

In [ ]:
df.value_counts()#count occurrences of unique values.

species  island  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  sex
Gentoo   Biscoe  59.6            17.0           230.0              6050.0       MALE      1
Adelie   Biscoe  34.5            18.1           187.0              2900.0       FEMALE    1
                 35.0            17.9           190.0              3450.0       FEMALE    1
                                                192.0              3725.0       FEMALE    1
                 35.3            18.9           187.0              3800.0       FEMALE    1
                                                                                         ..
                 38.1            16.5           198.0              3825.0       FEMALE    1
                 37.9            18.6           193.0              2925.0       FEMALE    1
                                                172.0              3150.0       FEMALE    1
                 37.8            20.0           190.0              4250.0       MALE      1
                                 18.3           174.0              3400.0       FEMALE    1
Name: count, Length: 333, dtype: int64

In [ ]:
df[2:11:2]#display or select particular data using filter

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
6,Adelie,Torgersen,38.9,17.8,181.0,3625.0,FEMALE
8,Adelie,Torgersen,34.1,18.1,193.0,3475.0,NaN
10,Adelie,Torgersen,37.8,17.1,186.0,3300.0,NaN

In [ ]:
df[['species','body_mass_g']] #varname[[col1,col2]]

    species  body_mass_g
0    Adelie       3750.0
1    Adelie       3800.0
2    Adelie       3250.0
3    Adelie          NaN
4    Adelie       3450.0
..      ...          ...
339  Gentoo          NaN
340  Gentoo       4850.0
341  Gentoo       5750.0
342  Gentoo       5200.0
343  Gentoo       5400.0

[344 rows x 2 columns]

In [ ]:
df.columns

Index(['species', 'island', 'bill_length_mm', 'bill_depth_mm',
       'flipper_length_mm', 'body_mass_g', 'sex'],
      dtype='object')

In [ ]:
df[['species','island','body_mass_g'][0:10:2]]    #df[['column1'.'column2','column3'][start:stop:step]]

    species  body_mass_g
0    Adelie       3750.0
1    Adelie       3800.0
2    Adelie       3250.0
3    Adelie          NaN
4    Adelie       3450.0
..      ...          ...
339  Gentoo          NaN
340  Gentoo       4850.0
341  Gentoo       5750.0
342  Gentoo       5200.0
343  Gentoo       5400.0

[344 rows x 2 columns]

In [ ]:
df.get(['species','island','body_mass_g'])#display multiple columns.

    species     island  body_mass_g
0    Adelie  Torgersen       3750.0
1    Adelie  Torgersen       3800.0
2    Adelie  Torgersen       3250.0
3    Adelie  Torgersen          NaN
4    Adelie  Torgersen       3450.0
..      ...        ...          ...
339  Gentoo     Biscoe          NaN
340  Gentoo     Biscoe       4850.0
341  Gentoo     Biscoe       5750.0
342  Gentoo     Biscoe       5200.0
343  Gentoo     Biscoe       5400.0

[344 rows x 3 columns]

In [ ]:
df.head(3)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE

In [ ]:
df.take([3],axis=1)#display particular column but here we need to pass its index ans axis=1 for column

     bill_depth_mm
0             18.7
1             17.4
2             18.0
3              NaN
4             19.3
..             ...
339            NaN
340           14.3
341           15.7
342           14.8
343           16.1

[344 rows x 1 columns]

In [ ]:
df.take([5],axis=0)#display particular column but here we need to pass its index ans axis=0 for rows

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,MALE

**Handling missing data**

Q1 Find columns containing missing value

In [ ]:
df.columns[df.isnull().any()]

Index(['bill_length_mm', 'bill_depth_mm', 'flipper_length_mm', 'body_mass_g',
       'sex'],
      dtype='object')

Q2 Find the percentage of missing data

In [ ]:
df.isnull().sum()/len(df)*100

species              0.000000
island               0.000000
bill_length_mm       0.581395
bill_depth_mm        0.581395
flipper_length_mm    0.581395
body_mass_g          0.581395
sex                  3.197674
dtype: float64

#OR

In [14]:
df.isna().sum()/len(df)*100

species              0.000000
island               0.000000
bill_length_mm       0.581395
bill_depth_mm        0.581395
flipper_length_mm    0.581395
body_mass_g          0.581395
sex                  3.197674
dtype: float64

Q3 Drop the rows with massive values

In [15]:
df.dropna()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,MALE
...,...,...,...,...,...,...,...
338,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,FEMALE
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

Q4 Check for duplicate rows

In [16]:
df.duplicated().sum()

np.int64(0)

Q5 How to remove duplicate rows

In [17]:
df.drop_duplicates()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

Q6 what is shape and size of dataset

In [19]:
df.shape

(344, 7)

In [21]:
df.size

2408

Q7 Summary of dataset

In [22]:
df.describe(include='all')

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
count,344,344,342.000000,342.000000,342.000000,342.000000,333
unique,3,3,NaN,NaN,NaN,NaN,2
top,Adelie,Biscoe,NaN,NaN,NaN,NaN,MALE
freq,152,168,NaN,NaN,NaN,NaN,168
mean,NaN,NaN,43.921930,17.151170,200.915205,4201.754386,NaN
std,NaN,NaN,5.459584,1.974793,14.061714,801.954536,NaN
min,NaN,NaN,32.100000,13.100000,172.000000,2700.000000,NaN
25%,NaN,NaN,39.225000,15.600000,190.000000,3550.000000,NaN
50%,NaN,NaN,44.450000,17.300000,197.000000,4050.000000,NaN
75%,NaN,NaN,48.500000,18.700000,213.000000,4750.000000,NaN
max,NaN,NaN,59.600000,21.500000,231.000000,6300.000000,NaN

Q8 Count penguines per island

In [23]:
df['island'].value_counts()

island
Biscoe       168
Dream        124
Torgersen     52
Name: count, dtype: int64

In [25]:
df.head(2)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE

Q9 Find average bill_length and bill_depth for each species

In [26]:
df.groupby('species')[["bill_length_mm","bill_depth_mm"]].mean()

           bill_length_mm  bill_depth_mm
species
Adelie          38.791391      18.346358
Chinstrap       48.833824      18.420588
Gentoo          47.504878      14.982114

Q10 Sort dataset by flipper_length_mm in descending order

In [28]:
srt=df.sort_values('flipper_length_mm',ascending=False)
srt[['species','flipper_length_mm']].head()

    species  flipper_length_mm
283  Gentoo              231.0
335  Gentoo              230.0
333  Gentoo              230.0
285  Gentoo              230.0
309  Gentoo              230.0